### ISSUE TITLE
[FEAT]: Handle branches

### ISSUE THREAD

**Issue by andreaiaia** [kocierik/gitPullAll#2]
### Description

What about a way to update the main branch of all repos?

### Additional Information

At the moment the only behavior is to update the current branch of all the repos, it may be interesting to add an option to pull the main/master branch instead.

In my zshrc I have this function that I use to merge new changes of main to my current develop branch:

```
 # update the current branch with changes from main
function forward() {
    branch_name=$(git branch --show-current);
    git switch main; echo;
    git pull; echo;
    git switch $branch_name; echo;
    git rebase main; echo;
}
```

I think the rebase/merge should be omitted, a rebase/merge to every repo might seriously break things, but the part of switching to main, pull, and go back to the branch it was on might be useful.

The default behavior might be the current one, and then a flag like `-m` or something could activate the main/master pull.

**Comment by kocierik** [comment]
This is a good idea! I have added this functionality in the latest [commits](https://github.com/kocierik/GitPullAll/commit/10a088de71b2a5fb256c0031a7354058ee057258). 

ty @andreaiaia
